import { Typography, Button, Stack } from '@mui/material';
import { useNavigate } from 'react-router-dom';

export default function Hero() {
  const navigate = useNavigate();

  return (
    <>
      <Typography
        variant="h1"
        component="h1"
        gutterBottom
        sx={{
          fontSize: { xs: '2.5rem', md: '4rem' },
          fontWeight: 800,
          background: 'linear-gradient(90deg, #00e5ff 10%, #7c4dff 90%)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          mb: 2,
        }}
      >
        Luma AI
      </Typography>

      <Typography variant="h5" color="text.secondary" paragraph sx={{ maxWidth: 720, mb: 4 }}>
        Create polished tutorial videos generated by AI and instantly produce intelligent video
        clips for highlights, chapters, and sharing. Fast, simple, and tuned for creators and
        educators.
      </Typography>

      <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}>
        <Button
          variant="contained"
          size="large"
          onClick={() => navigate('/login')}
          sx={{ px: 5, py: 1.75 }}
        >
          Start Building
        </Button>
        <Button
          variant="outlined"
          color="inherit"
          size="large"
          onClick={() => navigate('/demo')}
          sx={{ px: 5, py: 1.75 }}
        >
          Try Demo
        </Button>
      </Stack>
    </>
  );
}
